### ISSUE TITLE
Run under Wine

### ISSUE THREAD

**Issue by iwex** [TablePlus/TablePlus#1423]
Hello! Is there any possibility to run TablePlus on Linux using Wine? What libraries should I install?

**Comment by huyphams** [comment]
Hi @iwex TablePlus Windows requires .Net 4.8 and that's all.

**Comment by iwex** [comment]
@huyphams I tried, but 
`0009:err:eventlog:ReportEventW L"Application: TablePlus.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.Runtime.Inter0009:fixme:advapi:DeregisterEventSource (0xcafe4242) stub

Unhandled Exception: System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.IntGetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TablePlus.App.Main()
wine: Unhandled exception 0xe0434352 in thread 9 at address 0x7b45889c (thread 0009), starting debugger...
`

**Comment by huyphams** [comment]
Thanks, let me check it!

**Comment by Salmondx** [comment]
I have the exact same issue under wine. Such a pity because linux doesn't have normal db clients :(

**Comment by Salmondx** [comment]
@huyphams sorry for a followup, but do you have any updates regarding this issue? I know that you are working on a new native version for linux, but I want to be able to run it on linux at least under wine because there are absolutely no alternatives of TablePlus on linux.

Thanks for your great app btw!

**Comment by brysonreece** [comment]
I'll bump this as well. Super interested in a license if this is possible.

**Comment by huyphams** [comment]
Hi, we're planning to release the Linux beta this month. so I think I will not investigate this issue. The Linux version will be free until it out of beta.

**Comment by rogierverbrugge** [comment]
@huyphams awesome! Switching to linux so it's awesome my favorite DB app is available soon!

**Comment by huyphams** [comment]
We have an alpha release now, https://tableplus.com/linux/install

Please note that:
- This is an Alpha Release (not Beta yet)
- It's expected to HAVE A LOT OF BUGS
- It LACKS A LOT OF FEATURES

We will release a new update every week to make it better!

**Comment by denysonique** [comment]
The Linux version as of 2023 is still lacking. 

Is there a way to run this under Wine?
