### ISSUE TITLE
Can't access database after update (System.Net.Sockets.SocketException)

### ISSUE THREAD

**Issue by davidbonting** [TablePlus/TablePlus#2144]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
**mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper**

2. Which TablePlus build number are you using (the number on the welcome screen, Ex: build 81):
**build 146**

3. The steps to reproduce this issue:
All my production databases aren't accessible anymore. Duo the following error:

```
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at TablePlus.Source.Service.SSH.StartSocket() in C:\Users\maverick\Documents\tableplus-windows\TablePlus\TablePlus\Source\Service\SSH.cs:line 393
```

![image](https://user-images.githubusercontent.com/6029739/96687307-ffe67600-137f-11eb-8df9-de5ec56b7f4b.png)

**Comment by davidbonting** [comment]
Ok, after several restarts it appears to be working. Since I just updated TablePlus it looked like the update caused it...
