### ISSUE TITLE
Database tables are not listed on Microsoft Azure 

### ISSUE THREAD

**Issue by utkuerturk** [TablePlus/TablePlus#54]
Hi, I can successfully connect to the MSSql database on Azure, but it does not display the tables.

It gives the following error message. _Invalid object name 'sys.login_token'_

Screenshot : https://i.hizliresim.com/ZE463A.png

Thanks

**Comment by huyphams** [comment]
Hi @utkuerturk I got this bug. There are two bugs:
- Table Listing are not showed in Azure.
- Table user is not existed.
I will test with Azure and build an hotfix for you, keep follow issue 😁

**Comment by arturolinares** [comment]
Also when creating a backup shows an error asking for the correct driver version.
<img width="330" alt="backup_database" src="https://user-images.githubusercontent.com/203078/30517853-091d718e-9b32-11e7-83e7-684c347af74c.png">

**Comment by huyphams** [comment]
Hi @arturolinares MS didn't have client on MacOS, backup/restore only support for MySQL and PostgreSQL

**Comment by wpitallo** [comment]
I am getting the same error:

{System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'sys.login_token'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at TableDependency.SqlClient.SqlTableDependency`1.CheckIfUserHasPermissions(String connectionString)
   at TableDependency.TableDependency`1..ctor(String connectionString, String tableName, IModelToTableMapper`1 mapper, IUpdateOfModel`1 updateOf, ITableDependencyFilter filter, DmlTriggerType dmlTriggerType, Boolean executeUserPermissionCheck)
   at

**Comment by kenji0911** [comment]
I got this problem too, 

how is this issue going? TAT

Any Follow-up?

thanks :)

**Comment by huyphams** [comment]
Fixed @kenji0911 @utkuerturk 
Please check out this build and let me know if it works for you 😄
<img width="1219" alt="screen shot 2018-02-14 at 11 09 15 am" src="https://user-images.githubusercontent.com/3654622/36187384-8402c974-1177-11e8-87f7-f08cd2df9797.png">

**Comment by Sennahoi** [comment]
Works for me. Awesome!
